server:
  port: 8761
eureka:
  instance:
#    hostname: eurekaserver
    ip-address: 192.168.99.100
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/
  server:
    waitTimeInMsWhenSyncEmpty: 3


    