eureka:
  instance:
    preferIpAddress: true
#    hostname: eurekaserver
    ip-address: 192.168.99.100
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/